### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Delvin09** [Snakerman7/SnakeGame#1]
1. Сгруппируй файлы в директориях.
2. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/MenuScene.cs#L18 зачем static? часть полей можно сделать readonly.
3. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/MenuItem.cs#L11 Type и Position нужно сделать ридонли.
4. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/ResourcesManager.cs#L5 and https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/BestScoreManager.cs почему не static?
5. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/EndGameScene.cs#L7 поля тоже можно сделать ридонли.
6. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/Point.cs#L5 свойства тоже можно сделать ридонли.
7. https://github.com/Snakerman7/SnakeGame/blob/master/SnakeGame/GUI.cs#L7 Position тоже выглядит как ридонли
8. Выведи константы для строк и для цветов или в отдельный класс, или в ресурс манагер

**Comment by Snakerman7** [comment]
1. https://github.com/Snakerman7/SnakeGame/commit/2a39c34d058db55607e6466e27baadd1b8e0dbd1
2. https://github.com/Snakerman7/SnakeGame/commit/841a8bbd76b1330b4c784b8466873cde7f713886
3. https://github.com/Snakerman7/SnakeGame/commit/5e89fdf589cdf7181c41dac80a5ef9f8de9631da
4. https://github.com/Snakerman7/SnakeGame/commit/fdd4df73b79f94d7896f0e385c3a98576fa9bf44
5. https://github.com/Snakerman7/SnakeGame/commit/9f2ba2ed574c31900e7c8ee3d03f25e02a4bbde1
6. https://github.com/Snakerman7/SnakeGame/commit/1af2e445999bb549b4b66d1e2225ad335cdf1b36
7. https://github.com/Snakerman7/SnakeGame/commit/481dd4dcbd6961328940548b1f8aec661d0e443a
8. https://github.com/Snakerman7/SnakeGame/commit/114b94c08451cc27e342c5ffe13cfe71d47c8297
